### ISSUE TITLE
Questions about the "datasets" package in "smokers.py"

### ISSUE THREAD

**Issue by foxlf823** [GiuseppeMarra/nmln#1]
Hello Giuseppe,

I am trying to run the "smokers.py" but failed. It seems that the reason is due to the "datasets" package.
I have found a public "datasets" package released by HuggingFace (https://pypi.org/project/datasets/), but it doesn't contain the function "ntp_dataset".
Is the "datasets" package written by yourself? If so, could you please release the package and the "smokers" dataset?

Thank you very much

**Comment by GiuseppeMarra** [comment]
Hi,

the datasets package was just a collection of methods for reading files. 
I fixed the dependency now.

The code is not very well-documented (since we are working on a new version).  This was more for reproducibility. Let me know if you need anything else!

**Comment by foxlf823** [comment]
Thank you for sharing code and data. All set!
